import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Character, GetCharacterResults } from '../types'
import Main from './Main'

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Next.js Material Typescript</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
				/>
			</Head>
		</div>
	)
}

export default Home
